### create user with email & password
POST http://localhost:3000/auth/signup/
Content-Type: application/json

{
  "email": "test@bla.bla",
  "password": "password"
}

### get user by id
GET http://localhost:3000/auth/1
Accept: application/json

### get all users
GET http://localhost:3000/auth
Accept: application/json

### find users by email
GET http://localhost:3000/auth?email=email@bla.bla
Accept: application/json

### remove user by id
DELETE http://localhost:3000/auth/5
Content-Type: application/json

### update user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "updated@bla.bla"
}
